// Generated by CoffeeScript 1.9.3
(function() {
  var Account, Addresses, Base, Promise, Transactions,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Addresses = require('./addresses');

  Transactions = require('./transactions');

  Base = require('./base');

  Promise = require('bluebird');

  module.exports = Account = (function(superClass) {
    extend(Account, superClass);

    function Account(arg) {
      var client, resource, wallet;
      resource = arg.resource, client = arg.client, wallet = arg.wallet;
      this.client = client;
      this.resource = resource;
      this.wallet = wallet;
      this.name = resource.name, this.balance = resource.balance, this.path = resource.path, this.pending = resource.pending, this.network = resource.network, this.pending_balance = resource.pending_balance, this.available_balance = resource.available_balance;
    }

    Account.prototype.addresses = function() {
      return this.getAssociatedCollection({
        collectionClass: Addresses,
        name: 'addresses'
      });
    };

    Account.prototype.pay = function(arg) {
      var confirmations, mfa_token, multiwallet, payees, redirect_uri, tx, wallet;
      payees = arg.payees, confirmations = arg.confirmations, redirect_uri = arg.redirect_uri, mfa_token = arg.mfa_token;
      if (!payees) {
        return Promise.reject(new Error('Payees must be specified'));
      }
      wallet = this.wallet;
      multiwallet = wallet.multiwallet;
      if (multiwallet == null) {
        return Promise.reject(new Error('You must unlock the wallet before attempting a transaction'));
      }
      tx = new Transactions({
        resource: this.resource.transactions({}),
        client: this.client
      });
      return tx.create({
        payees: payees,
        confirmations: confirmations,
        redirect_uri: redirect_uri
      }).then(function(payment) {
        return payment.sign({
          wallet: multiwallet
        });
      }).then(function(signedTx) {
        if (wallet.application != null) {
          if (mfa_token == null) {
            mfa_token = wallet.application.get_mfa();
          }
          return signedTx.approve({
            mfa_token: mfa_token
          }).then(function(signedTx) {
            return signedTx;
          });
        } else {
          return signedTx;
        }
      });
    };

    Account.prototype.transactions = function(query) {
      if (query == null) {
        query = {};
      }
      return this.getAssociatedCollection({
        collectionClass: Transactions,
        name: 'transactions',
        resource: this.resource.transactions(query)
      });
    };

    return Account;

  })(Base);

}).call(this);
