// Generated by CoffeeScript 1.8.0
(function() {
  var Address;

  module.exports = Address = (function() {
    function Address(_arg) {
      var client, resource;
      resource = _arg.resource, client = _arg.client;
      this.client = client;
      this.resource = resource;
      this.path = resource.path, this.string = resource.string, this.subscriptions = resource.subscriptions;
    }

    return Address;

  })();

}).call(this);
