// Generated by CoffeeScript 1.8.0
(function() {
  var Address, Addresses, Collection, Promise, promisify,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Address = require('./address');

  Collection = require('./collection');

  Promise = require('bluebird');

  promisify = Promise.promisify;

  module.exports = Addresses = (function(_super) {
    __extends(Addresses, _super);

    function Addresses() {
      return Addresses.__super__.constructor.apply(this, arguments);
    }

    Addresses.prototype.type = Address;

    Addresses.prototype.create = function() {
      this.resource.create = promisify(this.resource.create);
      return this.resource.create().then((function(_this) {
        return function(resource) {
          var address;
          address = new Address({
            resource: resource,
            client: _this.client
          });
          _this.add(address);
          return address;
        };
      })(this))["catch"](function(error) {
        throw new Error(error);
      });
    };

    return Addresses;

  })(Collection);

}).call(this);
