// Generated by CoffeeScript 1.8.0
(function() {
  var Address, Addresses, Collection,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Address = require('./address');

  Collection = require('./collection');

  module.exports = Addresses = (function(_super) {
    __extends(Addresses, _super);

    function Addresses() {
      return Addresses.__super__.constructor.apply(this, arguments);
    }

    Addresses.prototype.type = Address;

    Addresses.prototype.create = function(callback) {
      return this.resource().create((function(_this) {
        return function(error, resource) {
          var address;
          if (error) {
            return callback(error);
          }
          address = new Address(resource, _this.client());
          _this.add(address);
          return callback(null, address);
        };
      })(this));
    };

    return Addresses;

  })(Collection);

}).call(this);
