// Generated by CoffeeScript 1.8.0
(function() {
  var Address;

  module.exports = Address = (function() {
    function Address(resource, client, options) {
      this.client = function() {
        return client;
      };
      this.resource = function() {
        return resource;
      };
      this.path = resource.path;
      this.string = resource.string;
    }

    return Address;

  })();

}).call(this);
