// Generated by CoffeeScript 1.9.2
(function() {
  var Address;

  module.exports = Address = (function() {
<<<<<<< HEAD
    function Address(_arg) {
      var client, resource;
      resource = _arg.resource, client = _arg.client;
=======
    function Address(arg) {
      var client, resource;
      resource = arg.resource, client = arg.client;
>>>>>>> 4bf7ba31cdc3da6385dd1e0bd595dd70005e22d1
      this.client = client;
      this.resource = resource;
      this.path = resource.path, this.string = resource.string, this.subscriptions = resource.subscriptions;
    }

    return Address;

  })();

}).call(this);
