// Generated by CoffeeScript 1.8.0
(function() {
  var Application, Applications, Collection,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Application = require('./application');

  Collection = require('./collection');

  module.exports = Applications = (function(_super) {
    __extends(Applications, _super);

    function Applications() {
      return Applications.__super__.constructor.apply(this, arguments);
    }

    Applications.prototype.type = Application;

    Applications.prototype.key = 'name';

    Applications.prototype.create = function(content, callback) {
      return this.resource().create(content, (function(_this) {
        return function(error, resource) {
          var application;
          if (error) {
            return callback(error);
          }
          application = new Application(resource, _this.client());
          _this.add(content.name, application);
          return callback(null, application);
        };
      })(this));
    };

    return Applications;

  })(Collection);

}).call(this);
