// Generated by CoffeeScript 1.8.0
(function() {
  var Asset, Assets, Collection, Promise, promisify,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Asset = require('./asset');

  Collection = require('./collection');

  Promise = require('bluebird');

  promisify = Promise.promisify;

  module.exports = Assets = (function(_super) {
    __extends(Assets, _super);

    function Assets() {
      return Assets.__super__.constructor.apply(this, arguments);
    }

    Assets.prototype.type = Asset;

    Assets.prototype.create = function(_arg) {
      var name, network, protocol;
      name = _arg.name, network = _arg.network, protocol = _arg.protocol;
      if (network == null) {
        network = 'bcy';
      }
      if (protocol == null) {
        protocol = 'openassets';
      }
      this.resource.create = promisify(this.resource.create);
      return this.resource.create({
        name: name,
        network: network,
        protocol: protocol
      }).then((function(_this) {
        return function(resource) {
          var asset;
          asset = new Asset({
            resource: resource,
            client: _this.client,
            wallet: _this.wallet
          });
          _this.add(asset);
          return asset;
        };
      })(this))["catch"](function(error) {
        throw new Error(error);
      });
    };

    return Assets;

  })(Collection);

}).call(this);
