// Generated by CoffeeScript 1.8.0
(function() {
  var Asset, Assetes, Collection, Promise, promisify,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Asset = require('./asset');

  Collection = require('./collection');

  Promise = require('bluebird');

  promisify = Promise.promisify;

  module.exports = Assetes = (function(_super) {
    __extends(Assetes, _super);

    function Assetes() {
      return Assetes.__super__.constructor.apply(this, arguments);
    }

    Assetes.prototype.type = Asset;

    Assetes.prototype.create = function() {
      this.resource.create = promisify(this.resource.create);
      return this.resource.create().then((function(_this) {
        return function(resource) {
          var asset;
          asset = new Asset({
            resource: resource,
            client: _this.client
          });
          _this.add(asset);
          return asset;
        };
      })(this))["catch"](function(error) {
        throw new Error(error);
      });
    };

    return Assetes;

  })(Collection);

}).call(this);
