// Generated by CoffeeScript 1.8.0
(function() {
  var Asset;

  module.exports = Asset = (function() {
    function Asset(_arg) {
      var client, resource;
      resource = _arg.resource, client = _arg.client;
      this.client = client;
      this.resource = resource;
      this.name = resource.name, this.network = resource.network, this.protocol = resource.protocol, this.fungible = resource.fungible, this.locked = resource.locked;
    }

    return Asset;

  })();

}).call(this);
