<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0
(function() {
  var Base,
    __hasProp = {}.hasOwnProperty;
=======
// Generated by CoffeeScript 1.9.2
(function() {
  var Base,
    hasProp = {}.hasOwnProperty;
>>>>>>> 4bf7ba31cdc3da6385dd1e0bd595dd70005e22d1

  module.exports = Base = (function() {
    function Base() {}

<<<<<<< HEAD
    Base.prototype.getAssociatedCollection = function(_arg) {
      var callback, collectionClass, collectionInstance, name, options, resource;
      collectionClass = _arg.collectionClass, name = _arg.name, resource = _arg.resource, options = _arg.options, callback = _arg.callback;
      if (this["_" + name] != null) {
        return callback(null, this["_" + name]);
      }
      if (options == null) {
        options = {};
      }
=======
    Base.prototype.getAssociatedCollection = function(arg) {
      var callback, collectionClass, collectionInstance, name, options, resource;
      collectionClass = arg.collectionClass, name = arg.name, resource = arg.resource, options = arg.options, callback = arg.callback;
      if (this["_" + name] != null) {
        return callback(null, this["_" + name]);
      }
>>>>>>> 4bf7ba31cdc3da6385dd1e0bd595dd70005e22d1
      resource = resource || this.resource[name];
      collectionInstance = new collectionClass({
        resource: resource,
        client: this.client,
        options: options
      });
<<<<<<< HEAD
      return collectionInstance.loadCollection(options, function(error, collectionInstance) {
=======
      return collectionInstance.loadCollection(function(error, collectionInstance) {
>>>>>>> 4bf7ba31cdc3da6385dd1e0bd595dd70005e22d1
        if (error) {
          return callback(error);
        }
        this["_" + name] = collectionInstance;
        return callback(null, collectionInstance);
      });
    };

    Base.prototype.update = function(content, callback) {
      return this.resource.update(content, (function(_this) {
        return function(error, resource) {
          var key, val;
          if (error) {
            return callback(error);
          }
          _this.resource = resource;
          for (key in content) {
<<<<<<< HEAD
            if (!__hasProp.call(content, key)) continue;
=======
            if (!hasProp.call(content, key)) continue;
>>>>>>> 4bf7ba31cdc3da6385dd1e0bd595dd70005e22d1
            val = content[key];
            _this[key] = val;
          }
          return callback(null, _this);
        };
      })(this));
    };

    return Base;

  })();

}).call(this);
