// Generated by CoffeeScript 1.8.0
(function() {
  var Developer, Developers;

  Developer = require('./developer');

  module.exports = Developers = (function() {
    function Developers(resource, client) {
      this.client = function() {
        return client;
      };
      this.resource = function() {
        return resource;
      };
    }

    Developers.prototype.create = function(credentials, callback) {
      var email, newDevCreds, pubkey;
      email = credentials.email, pubkey = credentials.pubkey;
      newDevCreds = {
        email: email,
        pubkey: pubkey
      };
      return this.resource().create(newDevCreds, (function(_this) {
        return function(error, developerResource) {
          if (error) {
            return callback(error);
          }
          _this.client()._developer = new Developer(developerResource, _this.client());
          if (credentials.privkey) {
            _this.client().patchboard().context.authorize('Gem-Developer', credentials);
          }
          return callback(null, _this.client()._developer);
        };
      })(this));
    };

    return Developers;

  })();

}).call(this);
