// Generated by CoffeeScript 1.9.3
(function() {
  var Devices, Promise, promisify;

  Promise = require('bluebird');

  promisify = Promise.promisify;

  module.exports = Devices = (function() {
    function Devices(arg) {
      var client, resource;
      resource = arg.resource, client = arg.client;
      this.resource = resource;
      this.client = client;
    }

    Devices.prototype.create = function(arg) {
      var name, params, redirect_uri;
      name = arg.name, redirect_uri = arg.redirect_uri;
      params = {
        name: name
      };
      if (redirect_uri) {
        params.redirect_uri = redirect_uri;
      }
      this.resource.create = promisify(this.resource.create);
      return this.resource.create(params).then(function(authRequestResource) {
        return {
          device_token: authRequestResource.metadata.device_token,
          mfa_uri: authRequestResource.mfa_uri
        };
      })["catch"](function(error) {
        throw new Error(error);
      });
    };

    return Devices;

  })();

}).call(this);
