// Generated by CoffeeScript 1.9.2
(function() {
  var Devices;

  module.exports = Devices = (function() {
    function Devices(arg) {
      var client, resource;
      resource = arg.resource, client = arg.client;
      this.resource = resource;
      this.client = client;
    }

    Devices.prototype.create = function(arg, callback) {
      var redirect_uri;
      redirect_uri = arg.name;
      return this.resource.create(arguments[0], function(error, authRequestResource) {
        if (error) {
          return callback(error);
        }
        return callback(null, {
          device_token: authRequestResource.metadata.device_token,
          mfa_uri: authRequestResource.mfa_uri
        });
      });
    };

    return Devices;

  })();

}).call(this);
