// Generated by CoffeeScript 1.8.0
(function() {
  var Devices;

  module.exports = Devices = (function() {
    function Devices(_arg) {
      var client, resource;
      resource = _arg.resource, client = _arg.client;
      this.resource = resource;
      this.client = client;
    }

    Devices.prototype.create = function(_arg, callback) {
      var redirect_uri;
      redirect_uri = _arg.name;
      return this.resource.create(arguments[0], function(error, authRequestResource) {
        if (error) {
          return callback(error);
        }
        return callback(null, {
          device_token: authRequestResource.metadata.device_token,
          mfa_uri: authRequestResource.mfa_uri
        });
      });
    };

    return Devices;

  })();

}).call(this);
