// Generated by CoffeeScript 1.8.0
(function() {
  var Payment;

  module.exports = Payment = (function() {
    function Payment(resource, client, options) {
      this.resource = function() {
        return resource;
      };
      this.client = function() {
        return client;
      };
    }

    Payment.prototype.sign = function(wallet, callback) {
      var signature, signatures, transactionContent, txHash, _ref;
      _ref = wallet.prepareTransaction(this.resource()), signatures = _ref.signatures, txHash = _ref.txHash;
      signature = signatures[0];
      transactionContent = {
        transaction_hash: txHash,
        inputs: [
          {
            primary: signature
          }
        ]
      };
      return this.resource().sign(transactionContent, function(error, data) {
        return callback(error, data);
      });
    };

    return Payment;

  })();

}).call(this);
