// Generated by CoffeeScript 1.9.2
(function() {
  var Payment;

  module.exports = Payment = (function() {
    function Payment(resource, client, options) {
      this.resource = function() {
        return resource;
      };
      this.client = function() {
        return client;
      };
      this.outputs = resource.outputs, this.confirmations = resource.confirmations, this.fee = resource.fee;
    }

    Payment.prototype.sign = function(wallet, callback) {
      var ref, signature, signatures, transactionContent, txHash;
      ref = wallet.prepareTransaction(this.resource()), signatures = ref.signatures, txHash = ref.txHash;
      signature = signatures[0];
      transactionContent = {
        transaction_hash: txHash,
        inputs: [
          {
            primary: signature
          }
        ]
      };
      return this.resource().sign(transactionContent, function(error, data) {
        return callback(error, data);
      });
    };

    return Payment;

  })();

}).call(this);
