// Generated by CoffeeScript 1.8.0
(function() {
  var Rules;

  module.exports = Rules = (function() {
    function Rules(rulesResource, client) {
      this.client = function() {
        return client;
      };
      this.resource = function() {
        return rulesResource;
      };
    }

    return Rules;

  })();

}).call(this);
