// Generated by CoffeeScript 1.8.0
(function() {
  var Subscription;

  module.exports = Subscription = (function() {
    function Subscription(resource, client) {
      this.resource = function() {
        return resource;
      };
      client = function() {
        return client;
      };
    }

    return Subscription;

  })();

}).call(this);
