// Generated by CoffeeScript 1.8.0
(function() {
  var Collection, Subsciption, Subsciptions,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Subsciption = require('subscription');

  Collection = require('./collection');

  module.exports = Subsciptions = (function(_super) {
    __extends(Subsciptions, _super);

    function Subsciptions(resource, client) {
      this.client = function() {
        return client;
      };
      this.resource = function() {
        return resource;
      };
    }

    Subsciptions.prototype.create = function(content, callback) {
      content.subscribed_to = "address";
      return this.resource().create(content, (function(_this) {
        return function(error, resource) {
          var subscription;
          if (error) {
            return callback(error);
          }
          subscription = new Subscription(resource, client());
          return _this.add(subscription);
        };
      })(this));
    };

    return Subsciptions;

  })(Collection);

}).call(this);
