// Generated by CoffeeScript 1.8.0
(function() {
  var Transaction;

  module.exports = Transaction = (function() {
    function Transaction(resource, client, options) {
      this.client = function() {
        return client;
      };
      this.resource = function() {
        return resource;
      };
      this.data = resource.data;
    }

    return Transaction;

  })();

}).call(this);
