// Generated by CoffeeScript 1.9.2
(function() {
  var Collection, Transaction, Transactions,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Transaction = require('./transaction');

  Collection = require('./collection');

  module.exports = Transactions = (function(superClass) {
    extend(Transactions, superClass);

    function Transactions() {
      return Transactions.__super__.constructor.apply(this, arguments);
    }

    Transactions.prototype.type = Transaction;

    return Transactions;

  })(Collection);

}).call(this);
