// Generated by CoffeeScript 1.9.3
(function() {
  var Base, Devices, Promise, User, Wallet, promisify,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  Wallet = require('./wallet');

  Devices = require('./devices');

  Promise = require('bluebird');

  promisify = Promise.promisify;

  module.exports = User = (function(superClass) {
    extend(User, superClass);

    function User(arg) {
      var client, resource;
      resource = arg.resource, client = arg.client;
      this.client = client;
      this.resource = resource;
      this.email = resource.email, this.url = resource.url, this.first_name = resource.first_name, this.last_name = resource.last_name, this.user_token = resource.user_token, this.default_wallet = resource.default_wallet;
    }

    User.prototype.wallet = function() {
      if (this._wallet) {
        Promise.resolve(this._wallet);
      }
      this.resource.default_wallet.get = promisify(this.resource.default_wallet.get);
      return this.resource.default_wallet.get().then((function(_this) {
        return function(resource) {
          return _this._wallet = new Wallet({
            resource: resource,
            client: _this.client
          });
        };
      })(this))["catch"](function(error) {
        throw new Error(error);
      });
    };

    User.prototype.devices = function() {
      var devices, resource;
      resource = this.client.resources.devices_query({
        email: this.email
      });
      devices = new Devices({
        resource: resource,
        client: this.client
      });
      return Promise.resolve(devices);
    };

    return User;

  })(Base);

}).call(this);
