// Generated by CoffeeScript 1.9.1
(function() {
  var Base, Devices, User, Wallets,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Wallets = require('./wallets');

  Base = require('./base');

  Devices = require('./devices');

  module.exports = User = (function(superClass) {
    extend(User, superClass);

    function User(arg) {
      var client, resource;
      resource = arg.resource, client = arg.client;
      this.client = client;
      this.resource = resource;
      this.email = resource.email, this.url = resource.url, this.first_name = resource.first_name, this.last_name = resource.last_name, this.user_token = resource.user_token, this.default_wallet = resource.default_wallet;
    }

    User.prototype.wallet = function(callback) {
      var resource, wallets;
      if (this._wallet) {
        return callback(null, this._wallet);
      }
      resource = this.resource.wallets;
      wallets = new Wallets({
        resource: resource,
        client: this.client
      });
      return wallets.loadCollection(function(error, wallets) {
        if (error) {
          return callback(error);
        }
        this._wallet = wallets.get(0);
        return callback(null, this._wallet);
      });
    };

    User.prototype.devices = function(callback) {
      var devices, resource;
      resource = this.client.resources.devices_query({
        email: this.email
      });
      devices = new Devices({
        resource: resource,
        client: this.client
      });
      return callback(null, devices);
    };

    return User;

  })(Base);

}).call(this);
