// Generated by CoffeeScript 1.9.2
(function() {
  var Accounts, Base, CoinOp, MultiWallet, PassphraseBox, Wallet,
<<<<<<< HEAD
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };
=======
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;
>>>>>>> 4bf7ba31cdc3da6385dd1e0bd595dd70005e22d1

  Accounts = require('./accounts');

  Base = require('./base');

  CoinOp = require('coinop-node');

  PassphraseBox = CoinOp.crypto.PassphraseBox;

  MultiWallet = CoinOp.bit.MultiWallet;

<<<<<<< HEAD
  module.exports = Wallet = (function(_super) {
    __extends(Wallet, _super);

    function Wallet(_arg) {
      var application, client, multiwallet, resource;
      resource = _arg.resource, client = _arg.client, multiwallet = _arg.multiwallet, application = _arg.application;
      this.client = client;
      this.resource = resource;
      this.multiwallet = multiwallet;
      this.application = application;
      this.name = resource.name, this.cosigner_public_seed = resource.cosigner_public_seed, this.backup_public_seed = resource.backup_public_seed, this.primary_public_seed = resource.primary_public_seed, this.balance = resource.balance, this.default_account = resource.default_account, this.transactions = resource.transactions;
    }

=======
  module.exports = Wallet = (function(superClass) {
    extend(Wallet, superClass);

    function Wallet(arg) {
      var application, client, multiwallet, resource;
      resource = arg.resource, client = arg.client, multiwallet = arg.multiwallet, application = arg.application;
      this.client = client;
      this.resource = resource;
      this.multiwallet = multiwallet;
      this.application = application;
      this.name = resource.name, this.cosigner_public_seed = resource.cosigner_public_seed, this.backup_public_seed = resource.backup_public_seed, this.primary_public_seed = resource.primary_public_seed, this.balance = resource.balance, this.default_account = resource.default_account, this.transactions = resource.transactions;
    }

>>>>>>> 4bf7ba31cdc3da6385dd1e0bd595dd70005e22d1
    Wallet.prototype.accounts = function(callback) {
      return this.getAssociatedCollection({
        collectionClass: Accounts,
        name: 'accounts',
        callback: callback,
        options: {
          wallet: this
        }
      });
    };

<<<<<<< HEAD
    Wallet.prototype.unlock = function(_arg) {
      var passphrase, primary_seed;
      passphrase = _arg.passphrase;
      primary_seed = PassphraseBox.decrypt(passphrase, this.resource.primary_private_seed);
      this.multiwallet = new MultiWallet({
=======
    Wallet.prototype.unlock = function(passphrase) {
      var primary_seed;
      primary_seed = PassphraseBox.decrypt(passphrase, this.resource.primary_private_seed);
      return this.multiwallet = new MultiWallet({
>>>>>>> 4bf7ba31cdc3da6385dd1e0bd595dd70005e22d1
        "private": {
          primary: primary_seed
        },
        "public": {
          cosigner: this.resource.cosigner_public_seed,
          backup: this.resource.backup_public_seed
        }
      });
      return this;
    };

    Wallet.prototype.backup_key = function() {
      return this.multiwallet.trees.backup.seed.toString('hex');
    };

    return Wallet;

  })(Base);

}).call(this);
