// Generated by CoffeeScript 1.8.0
(function() {
  var Account, Application, Client, SCHEMES, User, Users, Wallet, set_application;

  SCHEMES = require('./context').SCHEMES;

  Application = require('./resources/application');

  Users = require('./resources/users');

  User = require('./resources/user');

  Account = require('./resources/account');

  Wallet = require('./resources/wallet');

  set_application = function(application, client) {
    return client.application = application;
  };

  module.exports = Client = (function() {
    function Client(patchboard) {
      this.patchboard = patchboard;
      this.resources = patchboard.resources;
      this.context = patchboard.context;
      this.users = new Users({
        resource: this.resources.users,
        client: this
      });
    }

    Client.prototype.authenticate_application = function(_arg, callback) {
      var admin_token, api_token, totp_secret;
      admin_token = _arg.admin_token, api_token = _arg.api_token, totp_secret = _arg.totp_secret;
      this.patchboard.context.authorize('Gem-Application', arguments[0]);
      this.authenticate_identify({
        api_token: api_token
      });
      return this.application({
        totp_secret: totp_secret
      }, function(error, application) {
        return callback(error, application);
      });
    };

    Client.prototype.authenticate_identify = function(_arg) {
      var api_token;
      api_token = _arg.api_token;
      return this.patchboard.context.authorize('Gem-Identify', arguments[0]);
    };

    Client.prototype.authenticate_device = function(_arg, callback) {
      var api_token, device_token, email;
      email = _arg.email, api_token = _arg.api_token, device_token = _arg.device_token;
      this.patchboard.context.authorize('Gem-Device', arguments[0]);
      this.authenticate_identify({
        api_token: api_token
      });
      return this.user({
        email: email
      }, function(error, user) {
        return callback(error, user);
      });
    };

    Client.prototype.application = function(_arg, callback) {
      var totp_secret;
      totp_secret = _arg.totp_secret;
      if (arguments.length === 1) {
        callback = arguments[0];
        totp_secret = null;
      }
      if (this._application) {
        return callback(null, this._application);
      }
      return this.resources.app.get((function(_this) {
        return function(error, resource) {
          if (error) {
            return callback(error);
          }
          _this._application = new Application({
            resource: resource,
            client: _this,
            totp_secret: totp_secret
          });
          return callback(null, _this._application);
        };
      })(this));
    };

    Client.prototype.user = function(_arg, callback) {
      var email, resource;
      email = _arg.email;
      resource = this.resources.user_query({
        email: email
      });
      return resource.get((function(_this) {
        return function(error, resource) {
          return callback(error, new User({
            resource: resource,
            client: _this
          }));
        };
      })(this));
    };

    return Client;

  })();

}).call(this);
