// Generated by CoffeeScript 1.8.0
(function() {
  var Account, Application, Client, Promise, SCHEMES, User, Users, Wallet, promisify, set_application;

  SCHEMES = require('./context').SCHEMES;

  Application = require('./resources/application');

  Users = require('./resources/users');

  User = require('./resources/user');

  Account = require('./resources/account');

  Wallet = require('./resources/wallet');

  Promise = require('bluebird');

  promisify = Promise.promisify;

  set_application = function(application, client) {
    return client.application = application;
  };

  module.exports = Client = (function() {
    function Client(patchboard) {
      this.patchboard = patchboard;
      this.resources = patchboard.resources;
      this.context = patchboard.context;
      this.users = new Users({
        resource: this.resources.users,
        client: this
      });
    }

    Client.prototype.authenticate_application = function(_arg) {
      var admin_token, api_token, totp_secret;
      admin_token = _arg.admin_token, api_token = _arg.api_token, totp_secret = _arg.totp_secret;
      this.patchboard.context.authorize('Gem-Application', arguments[0]);
      this.authenticate_identify({
        api_token: api_token
      });
      return this.application({
        totp_secret: totp_secret
      });
    };

    Client.prototype.authenticate_identify = function(_arg) {
      var api_token;
      api_token = _arg.api_token;
      return this.patchboard.context.authorize('Gem-Identify', arguments[0]);
    };

    Client.prototype.authenticate_device = function(_arg) {
      var api_token, device_token, email;
      email = _arg.email, api_token = _arg.api_token, device_token = _arg.device_token;
      this.patchboard.context.authorize('Gem-Device', arguments[0]);
      this.authenticate_identify({
        api_token: api_token
      });
      return this.user({
        email: email
      }).then(function(user) {
        user.resource.get = promisify(user.resource.get);
        return user.resource.get();
      }).then((function(_this) {
        return function(resource) {
          return new User({
            resource: resource,
            client: _this
          });
        };
      })(this))["catch"](function(error) {
        throw new Error(error);
      });
    };

    Client.prototype.application = function(_arg) {
      var totp_secret;
      totp_secret = _arg.totp_secret;
      if (this._application) {
        return Promise.resolve(this._application);
      }
      this.resources.app.get = promisify(this.resources.app.get);
      return this.resources.app.get().then((function(_this) {
        return function(resource) {
          return _this._application = new Application({
            resource: resource,
            client: _this,
            totp_secret: totp_secret
          });
        };
      })(this))["catch"](function(error) {
        return error;
      });
    };

    Client.prototype.user = function(_arg) {
      var email, resource;
      email = _arg.email;
      resource = this.resources.user_query({
        email: email
      });
      resource.email = email;
      return Promise.resolve(new User({
        resource: resource,
        client: this
      }));
    };

    return Client;

  })();

}).call(this);
