// Generated by CoffeeScript 1.9.3
(function() {
  var Client, Context, NETWORKS, Patchboard, Promise, URL;

  Patchboard = require("patchboard-js");

  Promise = require("bluebird");

  Patchboard.discover = Promise.promisify(Patchboard.discover);

  Context = require("./context");

  Client = require("./client");

  URL = "https://api.gem.co";

  NETWORKS = {
    testnet: "bitcoin_testnet",
    bitcoin_testnet: "bitcoin_testnet",
    testnet3: "bitcoin_testnet",
    bitcoin: "bitcoin",
    mainnet: "bitcoin"
  };

  module.exports = {
    client: function(options) {
      var url;
      if (options == null) {
        options = {};
      }
      if (this.patchboard != null) {
        return Promise.resolve(new Client(this.patchboard.spawn()));
      } else {
        url = options.url || URL;
        return Patchboard.discover(url, {
          context: Context
        }).then((function(_this) {
          return function(patchboard) {
            _this.patchboard = patchboard;
            return new Client(_this.patchboard);
          };
        })(this))["catch"](function(error) {
          throw new Error(error);
        });
      }
    }
  };

}).call(this);
