// Generated by CoffeeScript 1.9.1
(function() {
  var Client, Context, NETWORKS, Patchboard, URL;

  Patchboard = require("patchboard-js");

  Context = require("./context");

  Client = require("./client");

  URL = "https://api.gem.co";

  NETWORKS = {
    testnet: "bitcoin_testnet",
    bitcoin_testnet: "bitcoin_testnet",
    testnet3: "bitcoin_testnet",
    bitcoin: "bitcoin",
    mainnet: "bitcoin"
  };

  module.exports = {
    client: function(options, callback) {
      var url;
      if (arguments.length === 1) {
        callback = arguments[0];
        options = {};
      }
      if (this.patchboard != null) {
        return callback(null, new Client(this.patchboard.spawn()));
      } else {
        url = options.url || URL;
        return Patchboard.discover(url, {
          context: Context
        }, (function(_this) {
          return function(error, patchboard) {
            _this.patchboard = patchboard;
            if (callback) {
              return callback(error, new Client(_this.patchboard));
            }
          };
        })(this));
      }
    }
  };

}).call(this);
