// Generated by CoffeeScript 1.7.1
(function() {
  var Client;

  module.exports = Client = (function() {
    function Client(api) {
      this.api = api;
      this.resources = this.api.resources;
    }

    Client.prototype.developer = function() {
      return {
        create: (function(_this) {
          return function(credentials, callback) {
            return _this.resources.developers.create(credentials, function(error, developer) {
              if (this._developer == null) {
                if (error) {
                  callback(error);
                }
                this._developer = developer;
                if (credentials.privkey) {
                  this.resources.context.authorize;
                }
              }
              return callback(null, this._developer);
            });
          };
        })(this)
      };
    };

    return Client;

  })();

}).call(this);
